require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.3.3
  NewCops: enable

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: [ 'describe', 'context', 'it' ]

# Add additional configuration as needed
